ncbi_assemblies:
  - GCF_000001735.4
  - GCF_000002595.2

ncbi_genomes:
    Athaliana:
        assembly_id: "GCF_000001735.4"
        species: Athaliana
        
    Creinhardtii:
        assembly_id: "GCF_000002595.2"
        species: Creinhardtii

names:
  - Athaliana
  - Creinhardtii

species_name:
  - Athaliana
#  - Creinhardtii

